api {
  api_server: "http://apiserver:8008"
  web_server: "http://webserver:80"
  files_server: "http://fileserver:8081"
  credentials {
    access_key: "mlops_access_key_123"
    secret_key: "mlops_secret_key_123"
  }
}

sdk {
  aws {
    s3 {
      key: "minioadmin"
      secret: "minioadmin"
      region: "us-east-1"
      use_credentials_chain: false

      credentials: [
        {
          host: "minio:9000"
          key: "minioadmin"
          secret: "minioadmin"
          multipart: false
          secure: false
          verify: false
          region: "us-east-1"
        }
      ]
    }
  }
}