apiVersion: v1
kind: ConfigMap
metadata:
  name: mlops-config
  namespace: mlops-hw1
data:
  PYTHONPATH: "/app"

  CLEARML_API_HOST: "http://host.minikube.internal:8008"
  CLEARML_WEB_HOST: "http://host.minikube.internal:8080"
  CLEARML_FILES_HOST: "http://host.minikube.internal:8081"
  CLEARML_PROJECT: "ML-Service"

  S3_ENDPOINT_URL: "http://minio:9000"
  DVC_S3_BUCKET: "dvc-storage"
  CLEARML_OUTPUT_URI: "s3://minio:9000/clearml-artifacts"

  API_BASE_URL: "http://ml-api-service:8000/api/v1"