apiVersion: v1
kind: Secret
metadata:
  name: mlops-secret
  namespace: mlops-hw1
type: Opaque
stringData:
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "minioadmin"

  AWS_ACCESS_KEY_ID: "minioadmin"
  AWS_SECRET_ACCESS_KEY: "minioadmin"
  AWS_DEFAULT_REGION: "us-east-1"

  CLEARML_API_ACCESS_KEY: "TVHU7I3FZ42PLC26TE3RRNJSISZZ29"
  CLEARML_API_SECRET_KEY: "HMTLeE6NkeJh4rUy5JtFjsAknv1Y_KttQKR2aODVmSMo1ryjep8F7QMMZp15Z9pXqXo"