apiVersion: v1
kind: Service
metadata:
  name: victoriametrics
  namespace: mlops-hw1
spec:
  selector:
    app: victoriametrics
  ports:
    - name: http
      port: 8428
      targetPort: 8428
  type: ClusterIP